# Site Info
title:              "Rex"
description:        "description"
author_name:        "Rex Wang" # change this to your name
logo_url:           https://api.github.com/users/rexfwang # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://rexfwang.github.io # main url
baseurl:            /the-plain
permalink:          /:title # Post permalink
timezone:           America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
